name: Build SGA APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        workdir: .
        buildozer_version: stable
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: SGA-App
        path: bin/*.apk
